name: Deployment Action
uses: chrnorm/deployment-action@v2.0.5
permissions:
      deployments: write
deployments:
  environmentMapping:
    development:
      - ".*-unstable"
    testing:
      - ".*-testing"
    production:
      - ".*-stable"
